version: "3.8"
services:
  judge0:
    image: judge0/judge0:latest
    container_name: judge0
    ports:
      - "2358:2358"
    environment:
      - ENABLE_QUEUE=false
      - DEBUG=false
    restart: unless-stopped
